name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  conformity:
    runs-on: ubuntu-latest
    container:
        image: rrey/terraform-runner:0.3.1
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Generate plan
        run: |
            cd examples/basic-example/
            terraform init
            terraform plan -out $GITHUB_WORKSPACE/basic-example.out
            terraform show -json $GITHUB_WORKSPACE/basic-example.out > $GITHUB_WORKSPACE/basic-example.json
        env:
            GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Run conformity tests
        run: |
          conftest test basic-example.json

  integration:
    runs-on: ubuntu-latest
    container:
        image: rrey/terraform-runner:0.3.1
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install ruby deps
        run: bundle install

      - name: Install Python and deps
        run: apk add python3 py3-pip py3-cryptography py3-cffi ruby-webrick ruby-etc ruby-io-console  && pip3 install -r requirements.txt


      - name: Run integration tests
        run: bundle exec kitchen test
        env:
            AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
