name: CI
on:
- pull_request

jobs:
  integration:
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    grafana_version: ["6.4.5", "6.5.3", "6.6.2"]
    #    python_version: ["3.6"]
    container:
        image: rrey/terraform-runner:0.1
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install ruby deps
        run: |
            apk add ruby-webrick
            bundle install

      - name: Run integration tests
        run: kitchen test
        env:
            AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
